---

- name: Ensure .ssh directory exists one level up
  ansible.builtin.file:
    dest: "{{ dest_key | dirname | dirname }}/.ssh"
    mode: '0700'
    state: directory

- name: Install SSH private key
  ansible.builtin.copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: '0600'

- name: Install SSH public key
  ansible.builtin.copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: '0600'

- name: Start ssh-agent
  ansible.builtin.shell: eval "$(ssh-agent -s)"
  register: ssh_agent_output
  changed_when: false

- name: Ensure ssh-agent is running and add SSH private key
  ansible.builtin.shell: |
    eval $(ssh-agent -s)
    ssh-add "{{ dest_key }}"
  environment:
    SSH_AUTH_SOCK: "{{ lookup('env', 'SSH_AUTH_SOCK') }}"
    SSH_AGENT_PID: "{{ lookup('env', 'SSH_AGENT_PID') }}"
  register: ssh_agent_output
  changed_when: "'Identity added' in ssh_agent_output.stdout"
  become: true
