#!/bin/bash
set -e

# Install curl
if ! [ -x "$(command -v curl)" ]; then 
  sudo pacman -S curl --noconfirm
fi 

# Install Ansible
if ! [ -x "$(command -v ansible)" ]; then 
  sudo pacman -S ansible --noconfirm
fi 

# Install and configure ZSH4HUMANS
if command -v curl >/dev/null 2>&1; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh4humans/v5/install)"
else
  sh -c "$(wget -O- https://raw.githubusercontent.com/romkatv/zsh4humans/v5/install)"
fi

# Entry Point to Main Playbook
ansible-playbook main.yml --ask-vault-pass
