- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
    ansible_user: "vasu"
  pre_tasks:
    - name: Update Pacman repositories
      become: true
      pacman:
        update_cache: yes

  tasks:
    - name: Include SSH tasks
      include_tasks: tasks/ssh.yml
      tags:
        - ssh

    - name: Include Yay tasks
      include_tasks: tasks/yay.yml
      tags:
        - aur
        - yay

    - name: Include Chaotic AUR tasks
      include_tasks: tasks/chaotic-aur.yml
      tags:
        - aur
        - chaotic-aur

    - name: Include ZSH tasks
      include_tasks: tasks/zsh.yml
      tags:
        - zsh

    - name: Include Fonts tasks
      include_tasks: tasks/fonts.yml
      tags:
        - fonts

    - name: Include Hyprland Utils tasks
      include_tasks: tasks/hyprland-utils.yml
      tags:
        - hyprland-utils

    - name: Include Audio tasks
      include_tasks: tasks/audio.yml
      tags:
        - audio

    - name: Include Bluetooth tasks
      include_tasks: tasks/bluetooth.yml
      tags:
        - bluetooth

    - name: Include Brave tasks
      include_tasks: tasks/brave.yml
      tags:
        - brave

    - name: Include Firefox tasks
      include_tasks: tasks/firefox.yml
      tags:
        - firefox

    - name: Include Dev Deps
      include_tasks: tasks/dev.yml
      tags:
        - dev

    - name: Include Node tasks
      include_tasks: tasks/node.yml
      tags:
        - node

    - name: Include Rust tasks
      include_tasks: tasks/rust.yml
      tags:
        - rust

    - name: Include Neovim tasks
      include_tasks: tasks/neovim.yml
      tags:
        - neovim

    - name: Include Syncthing tasks
      include_tasks: tasks/syncthing.yml
      tags:
        - syncthing

    - name: Include Tmux tasks
      include_tasks: tasks/tmux.yml
      tags:
        - tmux

    - name: Include Dual Boot tasks
      include_tasks: tasks/dual_boot.yml
      tags:
        - dual-boot

    - name: Include Apps tasks
      include_tasks: tasks/apps.yml
      tags:
        - apps
