- name: Install essential applications using pacman
  become: yes
  package:
    name:
      - telegram-desktop
      - yt-dlp
      - mpv
      - flatpak
      - aria2
      - auto-cpufreq
      - appimagelauncher
      - btop
      - htop
      - fastfetch
      - gparted
      - hugo
      - jdk-openjdk
      - nvtop
      - onedrive-abraunegg
      - stremio
      - tailscale
      - p7zip
      - uwufetch
      - zoom
      - visual-studio-code-bin
      - vdesktop
      - qbittorrent-enhanced
      - cloudflare-warp-bin
      - ncdu
      - obsidian
    state: present
  tags:
    - essentials
    - install
    - pacman

- name: Install AUR application using yay
  become: yes
  yay:
    name: localsend-bin
    state: present
  tags:
    - essentials
    - install
    - aur
