- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

- name: Start ssh-agent
  shell: eval "$(ssh-agent -s)"
  register: ssh_agent_output
  changed_when: false
  tags:
    - dotfiles
    - install
    - ssh

- name: Add SSH private key to ssh-agent
  shell: ssh-add "{{ dest_key }}"
  environment:
    SSH_AUTH_SOCK: "{{ ssh_agent_output.stdout_lines[-1] | regex_replace('^.*? (.*?);.*$', '\\1') }}"
  tags:
    - dotfiles
    - install
    - ssh
