- name: Install Syncthing
  become: yes
  package:
    name: syncthing
    state: present
  tags:
    - dotfiles
    - install
    - syncthing

- name: Enable Syncthing service for user
  become: yes
  systemd:
    name: syncthing@{{ ansible_user }}.service
    enabled: yes
    state: started
  tags:
    - dotfiles
    - install
    - syncthing
